### ISSUE TITLE
Changes bundled but not sent to browser until secod run in a row

### ISSUE THREAD

**Issue by fcuenca** [nikku/karma-browserify#113]
I'm launching Karma with autoWatch=false, and then triggering the tests manually using the command line. When I introduce a change in a source file, I need to trigger the tests twice for the changes to be sent to the browser. The bundle seems to be created with the appropriate content each time, but it's not until the second execution that those changes can be seen. This is similar to #106, but without involving the configure parameter.

If I use autoWatch=true, karma picks up the changes immediately, but then I seldom run into the "tests run twice" issue (#67)

Has anyone seen this behaviour before?

My setup includes the 'reactify' transform, just in case it matters.

Thanks!
Fernando.

**Comment by bendrucker** [comment]
We'd need to have a repo that we can clone and run in order to diagnose your setup

**Comment by fcuenca** [comment]
Done! https://github.com/fcuenca/karma-browserify-issue-113

The README has instructions to run and reproduce.

BTW, I didn't have to add "reactify" for the issue to show up.

**Comment by garthenweb** [comment]
I am running into the same issue. Would love to find the a solution for it.
#114 was not helpful to me, ``bundleDelay`` option did not solve the problem. I am further working on Windows 7...

**Comment by nikku** [comment]
I had a look into your project today. Without `autoWatch=true` karma will not pick up test file changes, nor will karma-browserify. As a result changes in the test files will _never_ be picked up (I reproduced your steps).

Test changes not being picked up is the _expected_ behavior. Turn `autoWatch` on and you will be fine.

@garthenweb Feel free to provide a test setup that reproduces your issue and we will have a look into it.

**Comment by fcuenca** [comment]
Thanks for looking into this.

Do you mean that you reproduced my steps and changes are *never* picked up? or that you reproduced my steps, obtained the results as I indicate, and that those results are as expected?

**Comment by nikku** [comment]
I reproduced your steps and changes got _never_ picked up. I believe this is the intended behavior. Did n't look deeper into your bash scripts though.

**Comment by garthenweb** [comment]
@nikku Thank you for that hint. I am using Karma with Grunt and trigger a changes via grunt watch task. I guess this worked in other projects without Browserify. Do you have any recommendation regarding the usage of Karma with Grunt? I tried to set autoWatch to ``true``, but it throws an error after changing the file: There is no server listening on port 9876

Otherwise, I will try to have a deeper look into this issue (when my time allows it) and will hopefully come back to you with a solution or at least an example.

**Comment by nikku** [comment]
The best way to use karma-browserify in continuous testing scenarios is by specifying `autoWatch=true`. This ensures browserify (via watchify) figures out bundle changes and triggers a re-run of the test suite automatically.
